<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Symfony\\Polyfill\\Util\\' => array($vendorDir . '/symfony/polyfill-util'),
    'Symfony\\Polyfill\\Php56\\' => array($vendorDir . '/symfony/polyfill-php56'),
    'Seld\\CliPrompt\\' => array($vendorDir . '/seld/cli-prompt/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'PragmaRX\\Recovery\\' => array($vendorDir . '/pragmarx/recovery/src'),
    'PragmaRX\\Random\\' => array($vendorDir . '/pragmarx/random/src'),
    'PragmaRX\\Google2FA\\Tests\\' => array($vendorDir . '/pragmarx/google2fa/tests'),
    'PragmaRX\\Google2FA\\' => array($vendorDir . '/pragmarx/google2fa/src'),
    'ParagonIE\\HiddenString\\' => array($vendorDir . '/paragonie/hidden-string/src'),
    'ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'ParagonIE\\Certainty\\' => array($vendorDir . '/paragonie/certainty/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Michelf\\' => array($vendorDir . '/michelf/php-markdown/Michelf'),
    'League\\HTMLToMarkdown\\' => array($vendorDir . '/league/html-to-markdown/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'FastRoute\\' => array($vendorDir . '/nikic/fast-route/src'),
    'DivineOmega\\PasswordExposed\\' => array($vendorDir . '/divineomega/password_exposed/src'),
    'DivineOmega\\DOFileCache\\' => array($vendorDir . '/divineomega/do-file-cache/src'),
    'DivineOmega\\DOFileCachePSR6\\' => array($vendorDir . '/divineomega/do-file-cache-psr-6/src'),
    'Dice\\' => array($vendorDir . '/level-2/dice'),
    'Asika\\SimpleConsole\\' => array($vendorDir . '/asika/simple-console/src'),
);
